apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-iceberg
  namespace: data-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      hostAliases:
        - ip: "10.96.166.39" # minio-storage clusterip goes here
          hostnames:
            - "minio.internal"
        - ip: "10.96.3.204" # nessie clusterop goes here
          hostnames:
            - "nessie.internal"
      containers:
      - name: spark
        image: fownten/spark-iceberg:3.5.0_1.4.2
        ports:
          - containerPort: 8000 # spark master ui
          - containerPort: 10000 # SQL / Thrift server
        env:
          # point spark to our minio s3
          - name: AWS_ACCESS_KEY_ID
            value: "admin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "password123"
          - name: AWS_REGION
            value: "us-east-1"
        volumeMounts:
          - name: spark-conf-vol
            mountPath: "/etc/spark/conf"
      volumes:
        - name: spark-conf-vol
          configMap:
            name: spark-defaults
