apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-iceberg
  namespace: data-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: tabulario/spark-iceberg:3.5.0_1.4.2
        ports:
          - containerPort: 8000 # spark master ui
          - containerPort: 10000 # SQL / Thrift server
        env:
          # point spark to our minio s3
          - name: AWS_ACCESS_KEY_ID
            value: "admin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "password123"
          - name: AWS_REGION
            value: "us-east-1"
          # spark configuration for spark
          - name: SPARK_CONF_spark_sql_catalog_local
            value: "org.apache.iceberg.spark.SparkCatalog"
          - name: SPARK_CONF_spark_sql_catalog_local_type
            value: "hadoop"
          - name: SPARK_CONF_spark_sql_catalog_local_warehouse
            value: "s3a://warehouse/iceberg"
          - name: SPARK_CONF_spark_sql_catalog_local_endpoint
            value: "http://minio.storage-layer.svc.cluster.local:9000"
          # disable ssl and enable path-style access (required for minio)
          - name: SPARK_CONF_spark_sql_catalog_local_s3_path_style_access
            value: "true"
          - name: SPARK_CONF_spark_sql_catalog_local_s3_ssl_enabled
            value: "false"
          - name: SPARK_CONF_spark_sql_default_catalog
            value: "local"

