apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: data-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: projectnessie/nessie:latest
          ports:
            - containerPort: 19120 # rest api
          env:
            - name: QUARKUS_DYNAMODB_ENDPOINT
              value: "http://minio.storage-layer.svc.cluster.local:9000"
            - name: QUARKUS_S3_PATH_STYLE_ACCESS # needed for minio
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: data-layer
spec:
  ports:
  - port: 19120
    targetPort: 19120
  selector:
    app: nessie
