apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestor
  namespace: data-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
      - name: ingestor
        image: my-ingestor:v1
        imagePullPolicy: Never # crucial for local kind images
